Wait for settings to be initialized
wbstack/ui pull request #69
Opened 2021-03-25 16:28 UTC by toban

2021-03-25 16:40 UTC, addshore commented
CI should be fixed after https://github.com/wbstack/ui/pull/71

2021-03-25 16:55 UTC, addshore requested changes
This seems to work for the very initial load of the manage page for a single wiki.
however if you navigate back to the dashboard and select a new wiki you will not see the spinner again

2021-03-26 08:10 UTC, toban commented
> This seems to work for the very initial load of the manage page for a single wiki.
> however if you navigate back to the dashboard and select a new wiki you will not see the spinner again

clearing it before making the request now.

2021-03-26 09:13 UTC, addshore approved these changes

2021-03-26 09:13 UTC, merged