Clean up dashboard cards
wbstack/ui pull request #926
Opened 2024-11-18 10:55 UTC by AndrewKostka

Bug: [T373129](https://phabricator.wikimedia.org/T373129)
Bug: [T359530](https://phabricator.wikimedia.org/T359530)

2024-11-18 11:39 UTC, rosalieper commented
The delete wikibase card has become smaller (shrink). I did not see that in accepted criteria.

2024-11-22 10:46 UTC, dati18 approved these changes
I think it's good to go

2024-11-26 16:13 UTC, dati18 requested changes

2024-11-26 17:16 UTC, dati18 requested changes
896px for `FEATURES` cards also.

2024-12-02 14:16 UTC, dati18 approved these changes

2024-12-09 14:24 UTC, deer-wmde approved these changes

2024-12-09 14:29 UTC, rosalieper approved these changes

2024-12-09 15:33 UTC, merged